name: Build

on:
  push:
    branches-ignore:
      - "l10n_master"
  pull_request:
    branches:
      - master
  merge_group: {}

jobs:
  # Windows
  build_windows_clang:
    name: "🖥️ Windows"
    uses: ./.github/workflows/windows-build-clang.yaml
    with:
      cmakePreset: "Release-windows-clang"
      cachePrefix: ""
